uefi-build/common-functions: import OpenSSL when building SB
When building a platform with -D SECURE_BOOT_ENABLE=TRUE, also
import OpenSSL (reusing existing version or grabbing cached
archive from LinaroPkg where possible).

Adapted from Ard's upstream build.

Signed-off-by: Leif Lindholm <leif.lindholm@linaro.org>

diff --git a/common-functions b/common-functions
--- a/common-functions
+++ b/common-functions
@@ -84,3 +84,42 @@ function get_clang_version
 	clang_version=`$1 --version | head -1 | sed 's/^.*version\s*\([0-9]*\).\([0-9]*\).*/\1\2/g'`
 	echo "CLANG$clang_version"
 }
+
+function import_openssl
+{
+    cd CryptoPkg/Library/OpensslLib/
+    OPENSSL_VER=`ls EDKII_openssl-*.patch | sed 's/^.*-\([0-9.a-z]*\).patch/\1/'`
+    OPENSSL_TAR=openssl-${OPENSSL_VER}.tar.gz
+    OPENSSL_URL=http://www.openssl.org/source/${OPENSSL_TAR}
+    OPENSSL_DIR=openssl-${OPENSSL_VER}
+    OPENSSL_PATCH=EDKII_openssl-${OPENSSL_VER}.patch
+
+    # Don't re-import if already done
+    if [ "$OPENSSL_CONFIGURED" = "TRUE" -o -e "$WORKSPACE"/CryptoPkg/Include/openssl/opensslconf.h ]; then
+	echo "Using existing OpenSSL $OPENSSL_VER"
+	cd -
+	return 0
+    fi
+
+    # Use cached copy if available
+    if [ -f "$WORKSPACE"/LinaroPkg/"$OPENSSL_TAR" ]; then
+	tar xzf "$WORKSPACE"/LinaroPkg/"$OPENSSL_TAR"
+    else
+	wget -O - -q ${OPENSSL_URL} | tar xzf -
+    fi
+
+    echo "Importing OpenSSL $OPENSSL_VER"
+    ( cd ${OPENSSL_DIR}; patch -p0 -i ../${OPENSSL_PATCH} )
+    ./Install.sh
+
+    if [ $? -eq 0 ]; then
+	OPENSSL_CONFIGURED=TRUE
+    else
+	echo "OpenSSL $OPENSSL_VER import failed!" >&2
+	rm -rf $OPENSSL_TAR $OPENSSL_DIR
+	cd -
+	return 1
+    fi
+
+    cd - >/dev/null
+}
