common-functions: return error if openssl archieve failed to extract
Also prevents attempting to recursively remove / on failure...

Signed-off-by: Leif Lindholm <leif.lindholm@linaro.org>

diff --git a/common-functions b/common-functions
--- a/common-functions
+++ b/common-functions
@@ -172,6 +172,10 @@ function clone_process_openssl
         rm -rf openssl
     fi
     tar xzf "$OPENSSL_TAR"
+    if [ $? -ne 0 -o ! -d "OPENSSL_VER" ]; then
+	echo "OpenSSL import failed!"
+	return 1
+    fi
     if [ ! -d openssl ]; then
         mkdir openssl
     fi
