add arm-tf support to edk2-build.sh
- Add search_packages_path to common-functions.
- Change occurences of EDK2_DIR to WORKSPACE or
  `search_packages_path` in atf-build.sh.
- Look for arm-trusted-firmware directory if -a was
  not specified on command line to edk2-build.sh.
- Add required options to build Juno with arm-tf
  to edk2-platforms.config.

Signed-off-by: Leif Lindholm <leif.lindholm@linaro.org>

diff --git a/common-functions b/common-functions
--- a/common-functions
+++ b/common-functions
@@ -191,3 +191,21 @@ function import_openssl
     cd - >/dev/null
     return $RET
 }
+
+function search_packages_path
+{
+    file="$1"
+
+    IFS=:
+    for dir in $PACKAGES_PATH; do
+	if [ -e "$dir/$file" ]; then
+	    echo "$dir/$file"
+	    unset IFS
+	    return 0
+	fi
+    done
+
+    echo "$file not found in any directory on PACKAGES_PATH!" >&2
+    unset IFS
+    return 1
+}
